# Generated by Django 2.0.4 on 2018-04-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0009_auto_20180407_0540'),
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('photo', models.ImageField(default='/photos/default.png', upload_to='photos')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('contestants', models.ManyToManyField(to='user.Profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizer.Organizer')),
            ],
        ),
    ]
